import type { NextConfig } from "next";
import { FRONT_CHART_ID } from "./src/shared/maps";

/**
 * Everything under public/ is served with `Cache-Control: public, max-age=0`
 * — Next cannot know that a file there is stable. The plates and the chart
 * sheets are: they are regenerated by scripts, not edited between requests.
 * Without this the browser revalidates the 800 KB sheet on every mount of
 * the map, and a reader coming back to the chart from a location page
 * watches it print itself again while the 304s land.
 *
 * Development keeps the default, so a regenerated engraving shows up on the
 * next reload instead of an hour later.
 */
const ART_CACHE =
  process.env.NODE_ENV === "production"
    ? "public, max-age=3600, stale-while-revalidate=604800"
    : "public, max-age=0";

const nextConfig: NextConfig = {
  /**
   * React's <ViewTransition> — the leaves of the atlas turn instead of being
   * replaced (docs/01-app/02-guides/view-transitions.md). Experimental in
   * Next; a browser without the View Transitions API simply swaps the page
   * as before, so nothing here is load-bearing.
   */
  experimental: {
    viewTransition: true,
  },
  /**
   * The admin tooling (/admin/coords picker, /admin/review) writes to the
   * repo's files and has no auth — it exists for the editor's machine only.
   * Its routes use the `.dev.tsx`/`.dev.ts` extensions, which a production
   * build does not recognize: the deploy contains no admin code at all (and
   * stays fully static — no lambdas), instead of shipping guarded 404s.
   */
  pageExtensions:
    process.env.NODE_ENV === "production"
      ? ["ts", "tsx"]
      : ["dev.ts", "dev.tsx", "ts", "tsx"],
  /**
   * The front chart lives at "/", and /maps/<front> is not generated
   * (dynamicParams=false 404s it before any page code could redirect).
   * The sheet has already been promoted once (pacific → new-england) on a
   * live site, so the old address must keep leading to the chart. Derived
   * from FRONT_CHART_ID: promote a sheet and its region URL follows.
   */
  async redirects() {
    return [
      {
        source: `/maps/${FRONT_CHART_ID}`,
        destination: "/",
        permanent: false,
      },
    ];
  },
  async headers() {
    return ["maps", "plates", "bestiary", "paper"].map((dir) => ({
      source: `/${dir}/:path*`,
      headers: [{ key: "Cache-Control", value: ART_CACHE }],
    }));
  },
};

export default nextConfig;
