import type { NextConfig } from "next";

/**
 * Everything under public/ is served with `Cache-Control: public, max-age=0`
 * — Next cannot know that a file there is stable. The plates and the chart
 * sheets are: they are regenerated by scripts, not edited between requests.
 * Without this the browser revalidates the 800 KB sheet on every mount of
 * the map, and a reader coming back to the chart from a location page
 * watches it print itself again while the 304s land.
 *
 * Development keeps the default, so a regenerated engraving shows up on the
 * next reload instead of an hour later.
 */
const ART_CACHE =
  process.env.NODE_ENV === "production"
    ? "public, max-age=3600, stale-while-revalidate=604800"
    : "public, max-age=0";

const nextConfig: NextConfig = {
  /**
   * The admin tooling (/admin/coords picker, /admin/review) writes to the
   * repo's files and has no auth — it exists for the editor's machine only.
   * Its routes use the `.dev.tsx`/`.dev.ts` extensions, which a production
   * build does not recognize: the deploy contains no admin code at all (and
   * stays fully static — no lambdas), instead of shipping guarded 404s.
   */
  pageExtensions:
    process.env.NODE_ENV === "production"
      ? ["ts", "tsx"]
      : ["dev.ts", "dev.tsx", "ts", "tsx"],
  async headers() {
    return ["maps", "plates", "bestiary", "paper"].map((dir) => ({
      source: `/${dir}/:path*`,
      headers: [{ key: "Cache-Control", value: ART_CACHE }],
    }));
  },
};

export default nextConfig;
